### PR TITLE
Allow specifying additional compiler arguments

### PR DESCRIPTION
**Pull request by auke-**
The protoc compiler introduces new features from time to time and currently there is no way to use those features until support is added to this plugin.

This change allows one to specify additional compiler arguments, which allows for enabling new and experimental features of the protoc compiler, e.g. --experimental_allow_proto3_optional.

### CODE REVIEW

**Comment by os72** [comment]
Ack, thanks

**Comment by parthshyara** [comment]
@os72 Please push this change to maven central.

**Comment by os72** [comment]
(Are you guys using this in work context?)

**Comment by parthshyara** [comment]
Yes.

**Comment by os72** [comment]
Well if it has value for your employer, maybe they'd consider sponsorship? In the meantime it's just labor of love on my side

**Pull request merged**
