### PR TITLE
Avoid regeneration if we can be sure nothing has changed

### PR DESCRIPTION
**Pull request by DavyLandman**
First off, thanks for this maven plugin! It has helped when the original plugin couldn't.

## Context 
As was already requested in #41 we want to avoid generating code on every compile, since our protobuf file change rarely, while the rest does.

## Implementation 
The code was already using the `hasDelta` calls of the `BuildContext` class, but these defaulted to `true`. No idea why. I've now added the most simple check I could think of, if all the files in the output folder are newer than any of the files in the input folder, we don't have to regenerate. 

I think that the maven way would be to use the `StaleSourceScanner ` but as far as I can see that requires similiar file paths for source and target and only a switch in extension, this will be hard to get right with the code generator of protocol buffers & grpc.

I've tested it on a local project, and it works as expected, between protobuf changes: regeneration, between other changes: no regeneration's.

## Discussion 
The only thing I am not sure of is what if the compile fails halfway through. If we leave the successful files, that could have an impact on the heuristic? Since running the compile a second time, will skip the code generation (if you haven't actually fixed the source specs). Or could we clear out all generated files after an error? Here my maven knowledge fails.

### CODE REVIEW

**Comment by DavyLandman** [comment]
I propose the following solution to the discussion:

1. a successful generation without any errors writes a success.txt file in the output directory
2. the heuristic in this PR only fires if the success.txt file is in the output directory

**Comment by os72** [comment]
Ack, thanks, will check

**Comment by DavyLandman** [comment]
thanks for merging, what's your plan for the failing codegen scenario?

**Comment by os72** [comment]
Just saved your changes on a new branch for now, will need a bit of time to take a closer look

**Comment by DavyLandman** [comment]
sure, take your time, just ping me if you want someone to discuss options with.

**Comment by os72** [comment]
Hi @DavyLandman, this is now on master, with successFile marker and "optimizeCodegen" option (we could make default true if we feel confident). Could you give it a try?

**Comment by DavyLandman** [comment]
Looks good, works on my multi-module maven project. 

Promoting the optimizeCodegen for a while and later flipping the default looks like a sane plan. Thanks for taking time to add this feature.

**Comment by os72** [comment]
Thanks! I'm pondering whether to make it true right away..

**Comment by DavyLandman** [comment]
Maybe you should, it might mean a major version bump? (If you are following semver style)

Benefit of maven central and the configuration is that if users encounter problems, they could either use the older version, or use the flag to disable it completely.

**Comment by os72** [comment]
Yes worst case it can be disabled. Re major version, I let protobuf/protoc dictate that. I'm only left with the 4th digit :)

**Comment by os72** [comment]
Released in version 3.7.0.1. Thanks for the contribution!

**Pull request merged**
