### PR TITLE
Include maven types

### PR DESCRIPTION
**Pull request by jvanbaa13**
Added "includeMavenTypes" parameter to allow importing proto files from dependency jars (Issue #19 ). 
The allowed values for the "includeMavenTypes" parameter are:

- "none": Do not attempt to extract and proto files from any dependencies. (default)
- "dependency": Attempt to extract proto files from direct dependencies only.
- "transitive": Attempt to extract proto files from all dependencies in the dependency hierarchy.

### CODE REVIEW

**Comment by os72** [comment]
Thanks will have a look

**Comment by jvanbaa13** [comment]
Any chance on this being accepted?

**Comment by os72** [comment]
Absolutely, it's the most requested feature. Sorry I've been swamped, will need some time to test and verify. Thanks again for contributing

**Comment by jvanbaa13** [comment]
Great! I just wanted to check and see if it was still on your radar. Happy to contribute. Thanks for your work.

**Comment by os72** [comment]
Hi there, sorry about the long delay.. I've reviewed and refactored a bit, could you review and test on your end? (Your core additions were good, thanks. I mostly reorganized my code flow)

I changed the allowed values to `none/direct/transitive`

https://github.com/os72/protoc-jar-maven-plugin/tree/IncludeMavenTypes

Thanks!

**Comment by os72** [comment]
Released protoc-jar-maven-plugin 3.6.0.1

**Pull request merged**
